-- =============================================
-- 010_INSERT_SEED_DATA.sql
-- Seeds default Admin, Sub-Admin users and
-- sample Courses into the database.
--
-- ⚠️  IMPORTANT:
-- Passwords below are plain-text placeholders.
-- Replace them with bcrypt hashes generated by
-- the backend before running in production.
-- Default hash below = bcrypt('Admin@1234', 10)
-- =============================================

DECLARE @AdminHash    NVARCHAR(255) = '$2b$10$REPLACE_WITH_REAL_BCRYPT_HASH_FOR_ADMIN';
DECLARE @SubAdminHash NVARCHAR(255) = '$2b$10$REPLACE_WITH_REAL_BCRYPT_HASH_FOR_SUBADMIN';

-- -----------------------------------------------
-- Seed: Main Admin
-- -----------------------------------------------
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[Users]
    WHERE [email] = 'admin@trainingcenter.com'
)
BEGIN
    INSERT INTO [dbo].[Users] ([name], [email], [password], [role], [isActive])
    VALUES ('Main Admin', 'admin@trainingcenter.com', @AdminHash, 'ADMIN', 1);

    PRINT '✅ Main Admin user inserted.';
END
ELSE
BEGIN
    PRINT '⚠️ Main Admin already exists. Skipping.';
END;

-- -----------------------------------------------
-- Seed: Sub Admin
-- -----------------------------------------------
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[Users]
    WHERE [email] = 'subadmin@trainingcenter.com'
)
BEGIN
    INSERT INTO [dbo].[Users] ([name], [email], [password], [role], [isActive])
    VALUES ('Sub Admin', 'subadmin@trainingcenter.com', @SubAdminHash, 'SUB_ADMIN', 1);

    PRINT '✅ Sub Admin user inserted.';
END
ELSE
BEGIN
    PRINT '⚠️ Sub Admin already exists. Skipping.';
END;

-- -----------------------------------------------
-- Seed: Courses
-- -----------------------------------------------
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[Courses]
    WHERE [courseName] = 'Introduction to Programming'
)
BEGIN
    INSERT INTO [dbo].[Courses] ([courseName], [description], [duration], [status])
    VALUES (
        'Introduction to Programming',
        'Basic programming concepts and problem solving.',
        '3 Months',
        'ACTIVE'
    );

    PRINT '✅ Course "Introduction to Programming" inserted.';
END
ELSE
BEGIN
    PRINT '⚠️ Course "Introduction to Programming" already exists. Skipping.';
END;

IF NOT EXISTS (
    SELECT 1 FROM [dbo].[Courses]
    WHERE [courseName] = 'Advanced Web Development'
)
BEGIN
    INSERT INTO [dbo].[Courses] ([courseName], [description], [duration], [status])
    VALUES (
        'Advanced Web Development',
        'Advanced frontend and backend web development.',
        '6 Months',
        'ACTIVE'
    );

    PRINT '✅ Course "Advanced Web Development" inserted.';
END
ELSE
BEGIN
    PRINT '⚠️ Course "Advanced Web Development" already exists. Skipping.';
END;

IF NOT EXISTS (
    SELECT 1 FROM [dbo].[Courses]
    WHERE [courseName] = 'Database Design'
)
BEGIN
    INSERT INTO [dbo].[Courses] ([courseName], [description], [duration], [status])
    VALUES (
        'Database Design',
        'Database design, SQL and database management.',
        '3 Months',
        'ACTIVE'
    );

    PRINT '✅ Course "Database Design" inserted.';
END
ELSE
BEGIN
    PRINT '⚠️ Course "Database Design" already exists. Skipping.';
END;
